<?php
/**
 * Created by PhpStorm.
 * User: King
 * Date: 14-2-4
 * Time: 下午12:38
 */

/**
 * Implementation of hook_menu
 */
function OSMap_menu(){

    $items = array();
    $items['OSMap'] = array(
        'title' => 'OSMap',
        'description' => 'A map module for OpenScholar',
        'page callback' => 'OSMap_page', // call the page
        'access arguments' => array('access content'), //The argument below is recommended for all users to have access to a page.
    );
	
	$items['OSMap/list'] = array(
		'title' => 'list',
		'type' => MENU_DEFAULT_LOCAL_TASK,
		'weight' => -10,
	);
	
	
    return $items;
}

/**
 * Implementation of the output function
 */
function OSMap_page() {

    return 'This is a hello world test of OSMap';
}